import { DeviceControlItem } from '../inter/Interface1'

 export const deviceControls: DeviceControlItem[] = [
   // 设备1 -实操区射灯灯组 1---控制全部小灯
   {
     control_sub_id: "ed6839e106ae49cdb84d4b920772abd4",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备2 - 氛围灯带
   {
     control_sub_id: "6b3f2977496844fd879845645099c5dd",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备3 - 教室1行射灯1
   {
     control_sub_id: "1d6f7bb91c824668bec9a40fd0720146",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备4 - 教室2行射灯1
   {
     control_sub_id: "2303a8e63b524430ad872c653587fc7d",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备5 - 教室3行射灯1
   {
     control_sub_id: "129ae737e4534ad7810f824ab6c0fe6e",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备6 - 教室4行射灯1
   {
     control_sub_id: "e264629cd1c744c98c534d8f534b0356",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备7 - 教室5行射灯1
   {
     control_sub_id: "631f332e5b814726acd856a8f6b40d10",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备8 - 教室6行射灯1
   {
     control_sub_id: "dc87bfa72d0745f4a468a3818e4da223",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备9 - 教室7行射灯1
   {
     control_sub_id: "a02aee173a7b46b89315a60423e375eb",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备10 - 教室8行射灯1
   {
     control_sub_id: "feecc342d97749dfac992cc8103e3348",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备11 - 教室9行射灯1
   {
     control_sub_id: "46a32f06de184ac7815e8d4bfcce6c48",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备12 - 教室10行射灯1
   {
     control_sub_id: "ac8d971606a0448a94f2b8bf21a62271",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备13 - 教室11行射灯1
   {
     control_sub_id: "cc30e58a9cd44b138a24db565c41653b",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备14 - 实操区1行射灯1
   {
     control_sub_id: "1033cc1ffc974b50836020dd06110038",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备15 - 实操区2行射灯1
   {
     control_sub_id: "3e1fcedc89794db1926149cc1170489e",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备16 - 实操区3行射灯1
   {
     control_sub_id: "b3336b40cfe741e5a2610c85b0a14831",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备17 - 实操区4行射灯1
   {
     control_sub_id: "09c4be277a7943678cb5e1982bd41567",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备18 - 实操区5行射灯1
   {
     control_sub_id: "458c578f97764355acc180e19ecbe06b",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备19 - 实操区6行射灯1
   {
     control_sub_id: "603396ab55a04387a1a025a392f6f3ed",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备20 - 实操区7行射灯1
   {
     control_sub_id: "ea954931e6264c8db2c89bc0631ace3c",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备21 - 实操区环形灯带1
   {
     control_sub_id: "420dece3d98e41e8b4bac04cc825d6b2",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备22 - 实操区灯带灯组1 包括环形灯带及灯管
   {
     control_sub_id: "a22b228be3b540638a3af2350982549b",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备23 - 实操区线形灯带1----只有灯管
   {
     control_sub_id: "60e5b7d5b4034d09a59bbfcc4cf5b363",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备24 - 教学区射灯1----全部小灯
   {
     control_sub_id: "c9b6bf04da8c453ba5b37f7bd1bc8db9",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   },
   // 设备25 - 教学区线型灯带1----全部灯管
   {
     control_sub_id: "b4e3359c8c3c420faa81e2b0c7aed1e0",
     control_sub_state: '0', // 打开
     w_channel: 66,
     y_channel: 66,
     type_uuid: 'LIGHT_GROUP'
   }
  ]

export const deviceClass: DeviceControlItem[] =[
  // 设备24 - 教学区射灯1----全部小灯
  {
    control_sub_id: "c9b6bf04da8c453ba5b37f7bd1bc8db9",
    control_sub_state: '0', // 打开
    w_channel: 80,
    y_channel: 50,
    type_uuid: 'LIGHT_GROUP'
  },
  // 设备25 - 教学区线型灯带1----全部灯管
  {
    control_sub_id: "b4e3359c8c3c420faa81e2b0c7aed1e0",
    control_sub_state: '0', // 打开
    w_channel: 80,
    y_channel: 50,
    type_uuid: 'LIGHT_GROUP'
  },
  // 设备2 - 氛围灯带
  {
    control_sub_id: "6b3f2977496844fd879845645099c5dd",
    control_sub_state: '0', // 打开
    w_channel: 80,
    y_channel: 50,
    r_channel:255,
    g_channel:255,
    b_channel:255,
    type_uuid: 'LIGHT_GROUP'
  },

]

export const exper:DeviceControlItem[]=[
  // 设备22 - 实操区灯带灯组1 包括环形灯带及灯管
  {
    control_sub_id: "a22b228be3b540638a3af2350982549b",
    control_sub_state: '0', // 打开
    w_channel: 80,
    y_channel: 50,
    r_channel:255,
    g_channel:255,
    b_channel:255,
    type_uuid: 'LIGHT_GROUP'
  },
  // 设备1 -实操区射灯灯组 1---控制全部小灯
  {
    control_sub_id: "ed6839e106ae49cdb84d4b920772abd4",
    control_sub_state: '0', // 打开
    w_channel: 80,
    y_channel: 50,
    type_uuid: 'LIGHT_GROUP'
  },
]

export const per:DeviceControlItem[]=[
  // 设备24 - 教学区射灯1----全部小灯
  {
    control_sub_id: "c9b6bf04da8c453ba5b37f7bd1bc8db9",
    control_sub_state: '0', // 打开
    w_channel: 60,
    y_channel: 70,
    type_uuid: 'LIGHT_GROUP'
  },
  // 设备25 - 教学区线型灯带1----全部灯管
  {
    control_sub_id: "b4e3359c8c3c420faa81e2b0c7aed1e0",
    control_sub_state: '0', // 打开
    w_channel: 60,
    y_channel: 70,
    type_uuid: 'LIGHT_GROUP'
  },
  // 设备2 - 氛围灯带
  {
    control_sub_id: "6b3f2977496844fd879845645099c5dd",
    control_sub_state: '0', // 打开
    w_channel: 60,
    y_channel: 70,
    r_channel:240,
    g_channel:240,
    b_channel:255,
    type_uuid: 'LIGHT_GROUP'
  },
]


export const break1:DeviceControlItem[]=[
  // 设备24 - 教学区射灯1----全部小灯
  {
    control_sub_id: "c9b6bf04da8c453ba5b37f7bd1bc8db9",
    control_sub_state: '0', // 打开
    w_channel: 40,
    y_channel: 30,
    type_uuid: 'LIGHT_GROUP'
  },
  // 设备25 - 教学区线型灯带1----全部灯管
  {
    control_sub_id: "b4e3359c8c3c420faa81e2b0c7aed1e0",
    control_sub_state: '0', // 打开
    w_channel: 40,
    y_channel: 30,
    type_uuid: 'LIGHT_GROUP'
  },
  // 设备2 - 氛围灯带
  {
    control_sub_id: "6b3f2977496844fd879845645099c5dd",
    control_sub_state: '0', // 打开
    w_channel: 40,
    y_channel: 30,
    r_channel:255,
    g_channel:220,
    b_channel:150,
    type_uuid: 'LIGHT_GROUP'
  },
  // 设备22 - 实操区灯带灯组1 包括环形灯带及灯管
  {
    control_sub_id: "a22b228be3b540638a3af2350982549b",
    control_sub_state: '0', // 打开
    w_channel: 40,
    y_channel: 30,
    r_channel:255,
    g_channel:220,
    b_channel:150,
    type_uuid: 'LIGHT_GROUP'
  },
  // 设备1 -实操区射灯灯组 1---控制全部小灯
  {
    control_sub_id: "ed6839e106ae49cdb84d4b920772abd4",
    control_sub_state: '0', // 打开
    w_channel: 40,
    y_channel: 30,
    type_uuid: 'LIGHT_GROUP'
  },
]